update public.brand_domains d set logo = v.logo from (values
('Affligem Tripel','logos/affligem-tripel.svg'),
('Almaza Pilsener','logos/almaza-pilsener.svg'),
('Asahi Super Dry','logos/asahi-super-dry.webp'),
('Augustiner Helles','logos/augustiner-helles.svg'),
('Beck''s','logos/becks.svg'),
('Belhaven Scottish Stout','logos/belhaven-scottish-stout.svg'),
('Big Wave Golden Ale','logos/big-wave-golden-ale.webp'),
('Birra Moretti','logos/birra-moretti.webp'),
('Bitburger Radler','logos/bitburger-radler.webp'),
('Bloodline Blood Orange IPA','logos/bloodline-blood-orange-ipa.webp'),
('Blue Moon','logos/blue-moon.webp'),
('Brahma','logos/brahma.webp'),
('Bud Light','logos/bud-light.webp'),
('Budweiser','logos/budweiser.webp'),
('Carlsberg','logos/carlsberg.svg'),
('Carlsberg Elephant','logos/carlsberg-elephant.svg'),
('Castle Lager','logos/castle-lager.webp'),
('Chill Lemon','logos/chill-lemon.webp'),
('Chimay Blue','logos/chimay-blue.webp'),
('Coopers Pale Ale','logos/coopers-pale-ale.svg'),
('Coors Light','logos/coors-light.webp'),
('Corona Extra','logos/corona-extra.svg'),
('DAB Dortmunder Export','logos/dab-dortmunder-export.webp'),
('Daura','logos/daura.svg'),
('De Koninck','logos/de-koninck.svg'),
('Dos Equis Lager Especial','logos/dos-equis-lager-especial.webp'),
('Duvel','logos/duvel.svg'),
('Erdinger Weißbier','logos/erdinger-weissbier.svg'),
('Estrella Damm','logos/estrella-damm.svg'),
('Estrella Galicia','logos/estrella-galicia.webp'),
('Estrella Jalisco','logos/estrella-jalisco.webp'),
('Frisse Lentebok','logos/frisse-lentebok.webp'),
('Goose IPA','logos/goose-ipa.webp'),
('Grolsch','logos/grolsch.webp'),
('Grolsch Puur Weizen','logos/grolsch-puur-weizen.webp'),
('Guinness Draught','logos/guinness-draught.webp'),
('Harp Lager','logos/harp-lager.webp'),
('Hatuey Lager','logos/hatuey-lager.svg'),
('Heineken','logos/heineken.svg'),
('Heineken Silver','logos/heineken-silver.svg'),
('Hertog Jan','logos/hertog-jan.webp'),
('Hoegaarden','logos/hoegaarden.webp'),
('Hofbräu Dunkel','logos/hofbrau-dunkel.svg'),
('Hofbräu Münchner Weiße','logos/hofbrau-munchner-weisse.svg'),
('Hop Commander','logos/hop-commander.webp'),
('IJwit','logos/ijwit.svg'),
('Ichnusa Anima Sarda','logos/ichnusa-anima-sarda.webp'),
('Kirin Ichiban','logos/kirin-ichiban.svg'),
('Kronenbourg 1664','logos/kronenbourg-1664.svg'),
('La Chouffe Blonde','logos/la-chouffe-blonde.svg'),
('La Fin Du Monde','logos/la-fin-du-monde.webp'),
('Leffe Blonde','logos/leffe-blonde.webp'),
('Magna','logos/magna.webp'),
('Mahou Cinco Estrellas','logos/mahou-cinco-estrellas.svg'),
('Medalla Light','logos/medalla-light.webp'),
('Menabrea','logos/menabrea.webp'),
('Michelob Ultra','logos/michelob-ultra.webp'),
('Miller Lite','logos/miller-lite.webp'),
('Modelo Especial','logos/modelo-especial.webp'),
('Modelo Oro','logos/modelo-oro.webp'),
('Mythos','logos/mythos.svg'),
('Narragansett Lager','logos/narragansett-lager.webp'),
('Negra Modelo','logos/negra-modelo.webp'),
('Newcastle Brown Ale','logos/newcastle-brown-ale.svg'),
('Norrlands Guld','logos/norrlands-guld.svg'),
('Ocean SJU','logos/ocean-sju.webp'),
('Orion','logos/orion.webp'),
('Pacífico Clara','logos/pacifico-clara.svg'),
('Paulaner Hefe','logos/paulaner-hefe.webp'),
('Paulaner Hefe-Weißbier','logos/paulaner-hefe-weissbier.webp'),
('Peroni Nastro Azzurro','logos/peroni-nastro-azzurro.webp'),
('Peroni Original','logos/peroni-original.webp'),
('Pilsner Urquell','logos/pilsner-urquell.svg'),
('Presidente','logos/presidente.webp'),
('Pub Ale','logos/pub-ale.svg'),
('Quilmes','logos/quilmes.webp'),
('Radeberger Pilsner','logos/radeberger-pilsner.webp'),
('Red Stripe','logos/red-stripe.webp'),
('Ringnes','logos/ringnes.webp'),
('Rolling Rock Extra Pale','logos/rolling-rock-extra-pale.webp'),
('Sam Adams Boston Lager','logos/sam-adams-boston-lager.svg'),
('Samuel Adams Summer Ale','logos/samuel-adams-summer-ale.svg'),
('Sapporo Premium','logos/sapporo-premium.webp'),
('Singha','logos/singha.svg'),
('Smithwick''s','logos/smithwicks.svg'),
('Sol','logos/sol.webp'),
('Spaten Oktoberfest Ur-Märzen / Winter','logos/spaten-oktoberfest-ur-marzen-winter.webp'),
('Stella Artois','logos/stella-artois.webp'),
('Stiegl Goldbräu','logos/stiegl-goldbrau.webp'),
('Stone IPA','logos/stone-ipa.webp'),
('Super Bock','logos/super-bock.svg'),
('Tennent''s','logos/tennents.svg'),
('Texels Skuumkoppe','logos/texels-skuumkoppe.svg'),
('Tiger Beer','logos/tiger-beer.svg'),
('Tsingtao','logos/tsingtao.webp'),
('Tuborg','logos/tuborg.svg'),
('Tyskie','logos/tyskie.svg'),
('Victoria Bitter','logos/victoria-bitter.svg'),
('Weihenstephaner Hefeweissbier','logos/weihenstephaner-hefeweissbier.webp'),
('Wrench','logos/wrench.webp'),
('Żywiec','logos/zywiec.svg')
) as v(beer_name, logo) where d.beer_name = v.beer_name and d.logo is distinct from v.logo;